### ISSUE TITLE
Handling i18n

### ISSUE THREAD

**Issue by Wojtasik** [kjendrzyca/corpo-food#19]
We should consider i18n in our application. Any suggestion guys?

**Comment by grzegorzlada** [comment]
Good idea to implement both "corpo" polish, standard polish and chinese simplified. If there's no "ready to use tool" we can write our own stuff for that.

**Comment by kjendrzyca** [comment]
@grzegorzlada this is node, there is always a tool:
https://github.com/airbnb/polyglot.js
https://github.com/i18next/i18next
https://github.com/nodeca/babelfish/

Polyglot looks cool, but other solutions need investigation

**Comment by Wojtasik** [comment]
@kjendrzyca I agree. Polyglot looks clean and simple. Only the four pipelines for pluralization looks odd, but we can work with that.

**Comment by tarnas14** [comment]
dibs, will try to use polyglot :)
